### ISSUE TITLE
Does not seem to work with videojs V4.12

### ISSUE THREAD

**Issue by dkarchmer** [danielcebrian/rangeslider-videojs#11]
If I use the 4.12 JS from the CDN (instead of the video-js in the lib folder), it stops working 

<script src="//vjs.zencdn.net/4.12/video.js"></script>

Any plans to upgrade to recent version of VideoJS?

(I know it is work but it will be greatly appreciated)

**Comment by danielcebrian** [comment]
it is not possible to use a minified version, could you try the full uncompiled version?

**Comment by dkarchmer** [comment]
I tried without .min and still does not work.

I get:
"Uncaught TypeError: Cannot read property 'children' of undefined" in 
      line 466 in rangeslider.js: "videojs.SeekBar.prototype.options_.children.RSTimeBar={};"
and

"Uncaught TypeError: Cannot read property 'SeekRSBar' of undefined" in 
      line 149 in rangeslider.js: "this.box = this.components.SeekRSBar = this.rstb.SeekRSBar;"

**Comment by dkarchmer** [comment]
I am using:
    <link href="//vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
    <script src="//vjs.zencdn.net/4.12/video.js"></script>

**Comment by danielcebrian** [comment]
Sorry, but http://vjs.zencdn.net/4.12/video.js. This is the minify version of videojs, you have to download the videojs and compile by yourself and then use the unminify version of videojs in the 4.12 version. I have tested and it is working fine.
Best,
Daniel

**Comment by jothikannan** [comment]
Not working still the issue is persist

**Comment by danielcebrian** [comment]
You can't use the minimized version of video.js. Please, read my last comment. Even if you download this version you won't be able to use the plugin

**Comment by unimitypravin** [comment]
Not working. Am using unminified version. Still the issue is occured.

Facing 2 Issues by default even unminified.

For the first time am getting SeekBar is undefined in rangeslider plugin. after refreshing the page it will not occured. Randomly am getting "showstatics is undefined" message also.

**Comment by unimitypravin** [comment]
I did unminified by using unminify.com online tool. This is not working. Here is the link for origin src files https://gteavirtual.org/ova/index.php?r=site/page&view=explore. Now its works fine without any random issues.

It works :)
