### ISSUE TITLE
Error on initialisation

### ISSUE THREAD

**Issue by chaitanyya** [danielcebrian/rangeslider-videojs#18]
Uncaught TypeError: Cannot read property 'children' of undefined.

Error Line:
videojs.SeekBar.prototype.options_.children.RSTimeBar = {}; //Range Slider Time Bar

I'm using the latest version of video.js with sublime-skin. Is there anything that I'm doing wrong.

**Comment by danielcebrian** [comment]
It is the same issue as https://github.com/danielcebrian/rangeslider-videojs/issues/8. You will have to have an no minified version of videojs
