### ISSUE TITLE
Uncaught TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by chaitanyya** [danielcebrian/rangeslider-videojs#19]
I get this error when i try to set the slider when the video is not playing. But it works fine when it's playing. plus setValueSider is not working it's not even showing any errors.

**Comment by danielcebrian** [comment]
Could you explain a bit more please? Are you using .min version of videojs? how is your initialization of rangeslider?

**Comment by chaitanyya** [comment]
Okay. I some how managed to make it work but it's not working with the current version of videojs. I'm using the one present in your repository.

**Comment by danielcebrian** [comment]
Billy is trying to upgrade the plugin version in https://github.com/danielcebrian/rangeslider-videojs/issues/22. You can see the changes and talk with him if you are still interested
