### ISSUE TITLE
Unable to add new controls when we use Range slider plugin with video.js

### ISSUE THREAD

**Issue by jothikannan** [danielcebrian/rangeslider-videojs#20]
I need to add a new control button on the controlbar. but when the player have Range slider plugin integrated i can't add new control

Mycode to add new control button:

      videojs.Tweet = videojs.Button.extend({
      /** @constructor */
        init: function(player, options){
          videojs.Button.call(this, player, options);
          this.on('click', this.onClick);
        }
      });

      videojs.Tweet.prototype.onClick = function() {
        alert("TWEET!");
      };

      // Note that we're not doing this in prototype.createEl() because
      // it won't be called by Component.init (due to name obfuscation).
      var createTweetButton = function() {
        var props = {
            className: 'vjs-tweet-button vjs-control',
            innerHTML: '<div class="vjs-control-content"><span class="vjs-control-text">' + ('Tweet') + '</span></div>',
            role: 'button',
            'aria-live': 'polite', // let the screen reader user know that the text of the button may change
            tabIndex: 0
          };
        return videojs.Component.prototype.createEl(null, props);
      };

      var tweet;
      videojs.plugin('tweet', function() {
        var options = { 'el' : createTweetButton() };
        tweet = new videojs.Tweet(this, options);
        this.controlBar.el().appendChild(tweet.el());
      });

      var vid = videojs("vid1", {
        plugins : { tweet : {} }
      });
 

But when i try it without the range slider, i can see the my new Button the Control bar.

**Comment by danielcebrian** [comment]
I am not sure what it is happening. Have you seen the css of tweet hidden in the source code?  Maybe you are overlapping the code in css.

I would recommend to watch the css and see whether you have your code hidden or not

**Comment by jothikannan** [comment]
Thanks @danielcebrian  

i managed my self to fix this, i added the controls with Jquery append to add my controls

**Comment by danielcebrian** [comment]
Great!

**Comment by jothikannan** [comment]
Am closing this now
