### ISSUE TITLE
Not working with video.js 5 

### ISSUE THREAD

**Issue by jothikannan** [danielcebrian/rangeslider-videojs#24]
This is plugin is not working with video.js 5 

am getting following error

TypeError: videojs.Player is undefined
http://localhost/js/rangeslider.js
Line 403

TypeError: this.rstb is undefined
http://localhost/js/rangeslider.js
Line 146

**Comment by jothikannan** [comment]
After updated the plugin into Adapted Range slider version, getting following error

TypeError: videojs.extends is not a function
http://localhost/js/rangeslider.js
Line 517

**Comment by danielcebrian** [comment]
There is an issue for this in https://github.com/danielcebrian/rangeslider-videojs/issues/22
