### ISSUE TITLE
Strange issue with your given version of video.js and rangeslider.js

### ISSUE THREAD

**Issue by jothikannan** [danielcebrian/rangeslider-videojs#25]
Am using your plugin for my projects, am using same version of video.js and rangeslider given in the download

am getting some weired javascript error from rangeslider.js inconsistently, meaning it causing the error sometime and sometime not, this is weired to me, so i can't judge what is the issue

`Uncaught TypeError: Cannot read property 'SeekRSBar' of undefined; url: js/rangeslider.js; line: 146; col: 52`

Some where i see that we need to update video.js version and rangeslider.js version as well, i tried both whatever i do am getting some new errors, due to this error all my videoplayer got broken as attached in the image

am runnig out of time for my project, any help on this could be highly appricateable ..

![3](https://cloud.githubusercontent.com/assets/4100047/11240246/2610df76-8e17-11e5-949f-66c738ecbb62.png)

**Comment by danielcebrian** [comment]
This plugin only works with videojs until the version 4.2. I have added a text in the Readme.md that said that "this plugin will no longer be maintained. Welcome those who want to continue the project."

You are trying to use videojs 5 and you get this error. I am in other projects and I don't have enough time to fix this. Please, let me know if you are interested to adapt to version 5.

**Comment by danielcebrian** [comment]
Continue talking of this in https://github.com/danielcebrian/rangeslider-videojs/issues/22

**Comment by jothikannan** [comment]
Thanks for your kind action on this, i solved the issue myslef, however i am having some queries and doubts, how could i contact you ? shall i send email to you ?
